"""
Export every tensor in the fine-tuned F_GENERIC checkpoint to a C99 header of static const
float arrays, plus a JSON architecture-metadata file, for the runtime-free C/NEON
reimplementation (M5). No ONNX Runtime, PyTorch, or TensorFlow Lite in the final C path --
this script is the only place PyTorch is used, purely to read the checkpoint tensors.
"""
import argparse
import json
import re
from pathlib import Path

import numpy as np
import torch

CKPT = "/content/project/checkpoints/F_GENERIC.tar"
OUT_H = "/content/project/mobile/c_neon/generated/ulunas_weights.h"
OUT_JSON = "/content/project/mobile/c_neon/generated/ulunas_arch.json"


def c_name(torch_name):
    return "w_" + re.sub(r"[^0-9a-zA-Z_]", "_", torch_name)


def fold_batchnorm(sd):
    """Fold the fixed C graph's 22 eval BNs, including grouped deconvolutions.

    Pointwise stages are Conv2d even in the decoder. Only decoder dconv/ops
    stages are ConvTranspose2d. Reject unexpected BN coverage/layouts.
    Use float32 scale/shift arithmetic to match batchnorm_apply (eps=1e-5).
    """
    folded = dict(sd)
    covered = set()
    for side, blocks in (("encoder.en_convs", ("ops", "mb", "dws", "mb", "dws")),
                         ("decoder.de_convs", ("dws", "mb", "dws", "mb", "ops"))):
        for index, kind in enumerate(blocks):
            stages = {"ops": (("ops", 1, 1),),
                      "mb": (("pconv1", 0, 2), ("dconv", 1, None), ("pconv2", 0, 2)),
                      "dws": (("pconv", 0, 2), ("dconv", 1, None))}[kind]
            for stage, conv_index, groups in stages:
                prefix = f"{side}.{index}.{stage}"
                conv = f"{prefix}.{conv_index}"
                bn = f"{prefix}.{conv_index + 1}"
                def array(key):
                    return sd[key].detach().cpu().numpy().astype(np.float32)
                w, b = array(conv + ".weight"), array(conv + ".bias")
                gamma, beta = array(bn + ".weight"), array(bn + ".bias")
                mean, var = array(bn + ".running_mean"), array(bn + ".running_var")
                if w.ndim != 4 or any(a.shape != b.shape for a in (gamma, beta, mean, var)):
                    raise ValueError(f"Unexpected conv/BN shape: {prefix}")
                scale = gamma / np.sqrt(var + np.float32(1e-5))
                shift = beta - mean * scale
                groups = len(b) if groups is None else groups
                transpose = side.startswith("decoder") and stage in ("ops", "dconv")
                if transpose:
                    # [groups, Cin/groups, Cout/groups, KT, KF]
                    if w.shape[0] % groups or w.shape[1] * groups != len(b):
                        raise ValueError(f"Unexpected deconv layout: {conv}")
                    grouped = w.reshape(groups, w.shape[0] // groups, *w.shape[1:])
                    new_w = (grouped * scale.reshape(groups, 1, -1, 1, 1)).reshape(w.shape)
                else:
                    if w.shape[0] != len(b):
                        raise ValueError(f"Unexpected conv layout: {conv}")
                    new_w = w * scale[:, None, None, None]
                new_b = b * scale + shift
                if not np.isfinite(new_w).all() or not np.isfinite(new_b).all():
                    raise ValueError(f"Non-finite folded parameters: {conv}")
                folded[conv + ".weight"] = torch.from_numpy(new_w)
                folded[conv + ".bias"] = torch.from_numpy(new_b)
                covered.add(bn + ".running_mean")
    actual = {key for key in sd if key.endswith(".running_mean")}
    if actual != covered or len(covered) != 22:
        raise ValueError(f"BN coverage mismatch: {actual ^ covered}")
    print(f"Folded {len(covered)} BatchNorm layers (eps=1e-5)")
    return folded


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fold-bn", action="store_true",
                        help="write separate ulunas_weights_folded.h / ulunas_arch_folded.json")
    parser.add_argument("--checkpoint", default=CKPT,
                        help=f"checkpoint .tar to export from (default: {CKPT})")
    args = parser.parse_args()
    ckpt = torch.load(args.checkpoint, map_location="cpu")
    sd = ckpt["model"]
    if args.fold_bn:
        sd = fold_batchnorm(sd)
    out_h = OUT_H.replace(".h", "_folded.h") if args.fold_bn else OUT_H
    out_json = OUT_JSON.replace(".json", "_folded.json") if args.fold_bn else OUT_JSON
    Path(out_h).parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"/* AUTO-GENERATED by export_weights.py from {args.checkpoint}. Do not edit by hand. */",
        "#pragma once",
        "",
    ]
    if args.fold_bn:
        lines += ["#ifndef ULUNAS_BN_FOLDED", '#error "Folded weights require ULUNAS_BN_FOLDED"',
                  "#endif", "#define ULUNAS_WEIGHTS_BN_FOLDED 1", ""]
    else:
        lines += ["#ifdef ULUNAS_BN_FOLDED", '#error "Unfolded weights cannot skip BatchNorm"',
                  "#endif", ""]
    meta = {}
    total_floats = 0

    for name, tensor in sd.items():
        if tensor.dtype == torch.int64:
            continue  # num_batches_tracked, unused at inference
        arr = tensor.detach().numpy().astype("float32").flatten()
        cname = c_name(name)
        lines.append(f"static const int {cname}_numel = {arr.size};")
        lines.append(f"static const float {cname}[{arr.size}] = {{")
        # 12 values per line for readability
        def fmt(v):
            s = f"{v:.9g}"
            if "." not in s and "e" not in s and "E" not in s and "inf" not in s and "nan" not in s:
                s += ".0"
            return s + "f"

        for i in range(0, len(arr), 12):
            chunk = arr[i:i + 12]
            lines.append("  " + ", ".join(fmt(v) for v in chunk) + ",")
        lines.append("};")
        lines.append("")
        meta[name] = {"c_name": cname, "shape": list(tensor.shape), "numel": int(arr.size)}
        total_floats += arr.size

    with open(out_h, "w") as f:
        f.write("\n".join(lines))

    with open(out_json, "w") as f:
        json.dump(meta, f, indent=2)

    print(f"Exported {len(meta)} tensors, {total_floats} floats, to {out_h}")
    print(f"({total_floats * 4 / 1e6:.2f} MB as float32)")


if __name__ == "__main__":
    main()
