"""
Export every tensor in the fine-tuned F_GENERIC checkpoint to a C99 header of static const
float arrays, plus a JSON architecture-metadata file, for the runtime-free C/NEON
reimplementation (M5). No ONNX Runtime, PyTorch, or TensorFlow Lite in the final C path --
this script is the only place PyTorch is used, purely to read the checkpoint tensors.
"""
import json
import re
import sys

import torch

sys.path.insert(0, "/content/project/SEtrain_adapted")

CKPT = "/content/project/checkpoints/F_GENERIC.tar"
OUT_H = "/content/project/mobile/c_neon/generated/ulunas_weights.h"
OUT_JSON = "/content/project/mobile/c_neon/generated/ulunas_arch.json"


def c_name(torch_name):
    return "w_" + re.sub(r"[^0-9a-zA-Z_]", "_", torch_name)


def main():
    ckpt = torch.load(CKPT, map_location="cpu")
    sd = ckpt["model"]

    lines = [
        "/* AUTO-GENERATED by export_weights.py from checkpoints/F_GENERIC.tar. Do not edit by hand. */",
        "#pragma once",
        "",
    ]
    meta = {}
    total_floats = 0

    for name, tensor in sd.items():
        if tensor.dtype == torch.int64:
            continue  # num_batches_tracked, unused at inference
        arr = tensor.detach().numpy().astype("float32").flatten()
        cname = c_name(name)
        lines.append(f"static const int {cname}_numel = {arr.size};")
        lines.append(f"static const float {cname}[{arr.size}] = {{")
        # 12 values per line for readability
        def fmt(v):
            s = f"{v:.9g}"
            if "." not in s and "e" not in s and "E" not in s and "inf" not in s and "nan" not in s:
                s += ".0"
            return s + "f"

        for i in range(0, len(arr), 12):
            chunk = arr[i:i + 12]
            lines.append("  " + ", ".join(fmt(v) for v in chunk) + ",")
        lines.append("};")
        lines.append("")
        meta[name] = {"c_name": cname, "shape": list(tensor.shape), "numel": int(arr.size)}
        total_floats += arr.size

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines))

    with open(OUT_JSON, "w") as f:
        json.dump(meta, f, indent=2)

    print(f"Exported {len(meta)} tensors, {total_floats} floats, to {OUT_H}")
    print(f"({total_floats * 4 / 1e6:.2f} MB as float32)")


if __name__ == "__main__":
    main()
